package com.naveen.problems.strings;

// https://leetcode.com/problems/find-the-difference/
// You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Return the letter that was added to t.
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

public class Problem389_FindTheDifference {
    public char findTheDifference(String s, String t) {
        char xor = 0;
        for (char cs : s.toCharArray()) xor ^= cs;
        for (char ct : t.toCharArray()) xor ^= ct;
        return xor;
    }
}
